language: python

python:
  - "3.4"
  - "3.3"
  - "2.7"

env:
  - DJANGO="https://www.djangoproject.com/download/1.7.b4/tarball/"
  - DJANGO="django==1.6.5"
  - DJANGO="django==1.5.8"
  - DJANGO="django==1.4.2"
  - DJANGO="django==1.4.15"


matrix:
  exclude:
    - python: 3.3
      env: DJANGO="django==1.4.2"
    - python: 3.3
      env: DJANGO="django==1.4.15"
    - python: 3.4
      env: DJANGO="django==1.4.2"
    - python: 3.4
      env: DJANGO="django==1.4.15"

services:
  - postgresql

install:
  - pip install $DJANGO --use-mirrors
  - pip install psycopg2==2.5.3 --use-mirrors

branches:
  only:
    - master

script:
  - python runtests.py

before_script:
  - createdb test

notifications:
  email:
    recipients:
      - dijakroot@gmail.com
    on_success: change
    on_failure: change
